// ============================================================
// ROUKI FASHION — Données Produits & Services
// ============================================================

import robeWax from './assets/images/model_robe_wax_orange.jpg';
import ensembleBleu from './assets/images/model_ensemble_bleu.jpg';
import robeNoire from './assets/images/model_robe_noire_gold.jpg';
import ensembleVert from './assets/images/model_ensemble_vert.jpg';
import jupeRose from './assets/images/model_jupe_rose.jpg';
import boubouBordeaux from './assets/images/model_boubou_bordeaux.jpg';

export const WHATSAPP_NUMBER = '+2290143271803';
export const WHATSAPP_LINK = `https://wa.me/${WHATSAPP_NUMBER.replace(/\D/g, '')}`;
export const PHONE_NUMBER = '+229 01 43 27 18 03';

export const categories = [
  { id: 'all', label: 'Tout', icon: 'grid' },
  { id: 'robes', label: 'Robes', icon: 'dress' },
  { id: 'ensembles', label: 'Ensembles', icon: 'layers' },
  { id: 'jupes', label: 'Jupes', icon: 'circle' },
  { id: 'boubous', label: 'Boubous', icon: 'star' },
  { id: 'enfant', label: 'Enfant', icon: 'heart' },
];

export const products = [
  {
    id: 1,
    name: 'Robe Wax Soleil',
    category: 'robes',
    categoryLabel: 'Robe',
    image: robeWax,
    price: '45 000 FCFA',
    rating: 4.9,
    reviews: 38,
    badge: 'Nouveau',
    description:
      "Une création exceptionnelle en wax 100 % africain aux couleurs de l'aurore. Silhouette fluide avec manches à volants caractéristiques de notre savoir-faire. Idéale pour les cérémonies, mariages et sorties élégantes.",
    specs: {
      Matière: 'Wax 100% coton',
      Coupe: 'Robe longue',
      Finition: 'Couture main',
      Délai: '7 à 10 jours',
    },
    isNew: true,
  },
  {
    id: 2,
    name: 'Ensemble Pagne Royal',
    category: 'ensembles',
    categoryLabel: 'Ensemble',
    image: ensembleBleu,
    price: '55 000 FCFA',
    rating: 4.8,
    reviews: 24,
    badge: null,
    description:
      "Ensemble deux pièces en pagne wax bleu et blanc. Jupe portefeuille assortie à un top peplum à col. Allure royale, confort absolu. La tenue parfaite pour impressionner en toutes circonstances.",
    specs: {
      Matière: 'Pagne wax',
      Coupe: 'Ensemble 2 pièces',
      Finition: 'Broderie main',
      Délai: '10 à 14 jours',
    },
    isNew: false,
  },
  {
    id: 3,
    name: 'Robe Nuit Dorée',
    category: 'robes',
    categoryLabel: 'Robe',
    image: robeNoire,
    price: '65 000 FCFA',
    rating: 5.0,
    reviews: 15,
    badge: 'Exclusif',
    description:
      "Robe de soirée noire ajustée avec broderies dorées sur toute la longueur et une fente latérale audacieuse. Pièce maîtresse de notre collection Prestige. Pour les femmes qui savent ce qu'elles valent.",
    specs: {
      Matière: 'Tissu satiné + broderies or',
      Coupe: 'Robe longue ajustée',
      Finition: 'Broderie artisanale',
      Délai: '14 à 21 jours',
    },
    isNew: false,
  },
  {
    id: 4,
    name: 'Ensemble Émeraude',
    category: 'ensembles',
    categoryLabel: 'Ensemble',
    image: ensembleVert,
    price: '58 000 FCFA',
    rating: 4.7,
    reviews: 31,
    badge: 'Tendance',
    description:
      "Ensemble pantalon palazzo et veste courte en tissu kente vert et or. Un style moderne et affirmé qui mêle tradition africaine et coupe contemporaine. Parfait pour les femmes de caractère.",
    specs: {
      Matière: 'Tissu kente tissé',
      Coupe: 'Ensemble 2 pièces',
      Finition: 'Couture de précision',
      Délai: '10 à 14 jours',
    },
    isNew: false,
  },
  {
    id: 5,
    name: 'Jupe & Top Dentelle Rose',
    category: 'jupes',
    categoryLabel: 'Jupe & Top',
    image: jupeRose,
    price: '38 000 FCFA',
    rating: 4.8,
    reviews: 19,
    badge: null,
    description:
      "Ensemble jupe mi-longue et top épaule dénudée en dentelle rose poudré et blanc. Féminité absolue, légèreté et élégance. La pièce idéale pour un événement champêtre ou une sortie distinguée.",
    specs: {
      Matière: 'Dentelle + voile',
      Coupe: 'Jupe mi-longue + top',
      Finition: 'Appliqués dentelle',
      Délai: '7 à 10 jours',
    },
    isNew: true,
  },
  {
    id: 6,
    name: 'Grand Boubou Bordeaux',
    category: 'boubous',
    categoryLabel: 'Boubou',
    image: boubouBordeaux,
    price: '75 000 FCFA',
    rating: 5.0,
    reviews: 22,
    badge: 'Premium',
    description:
      "Grand boubou en tissu bordeaux brodé de fils dorés avec soin. Allure royale et imposante. Cette pièce est la quintessence de l'élégance africaine de haut rang. Pour mariages, cérémonies officielles et événements d'exception.",
    specs: {
      Matière: 'Bazin riche brodé',
      Coupe: 'Grand boubou',
      Finition: 'Broderie or artisanale',
      Délai: '14 à 21 jours',
    },
    isNew: false,
  },
  {
    id: 100,
    name: 'Robe Collection ' + 1,
    category: 'robes',
    categoryLabel: 'Robe',
    image: '/robes/0876693e93c517871069826a54bc4209.jpg',
    price: '40 000 FCFA',
    rating: 4.8,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Robe de haute qualité avec un design unique.',
    specs: {
      Matière: 'Wax / Dentelle / Pagne',
      Coupe: 'Robe élégante',
      Finition: 'Couture soignée',
      Délai: '7 à 10 jours',
    },
    isNew: false,
  },
  {
    id: 101,
    name: 'Robe Collection ' + 2,
    category: 'robes',
    categoryLabel: 'Robe',
    image: '/robes/237db267371c438641b209266c47b0ff.jpg',
    price: '40 000 FCFA',
    rating: 4.8,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Robe de haute qualité avec un design unique.',
    specs: {
      Matière: 'Wax / Dentelle / Pagne',
      Coupe: 'Robe élégante',
      Finition: 'Couture soignée',
      Délai: '7 à 10 jours',
    },
    isNew: false,
  },
  {
    id: 102,
    name: 'Robe Collection ' + 3,
    category: 'robes',
    categoryLabel: 'Robe',
    image: '/robes/2f60e158684770385a7956cd79bdfbf0.jpg',
    price: '40 000 FCFA',
    rating: 4.8,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Robe de haute qualité avec un design unique.',
    specs: {
      Matière: 'Wax / Dentelle / Pagne',
      Coupe: 'Robe élégante',
      Finition: 'Couture soignée',
      Délai: '7 à 10 jours',
    },
    isNew: false,
  },
  {
    id: 103,
    name: 'Robe Collection ' + 4,
    category: 'robes',
    categoryLabel: 'Robe',
    image: '/robes/31d1f3b6552ba6409777ec3572ac4187.jpg',
    price: '40 000 FCFA',
    rating: 4.8,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Robe de haute qualité avec un design unique.',
    specs: {
      Matière: 'Wax / Dentelle / Pagne',
      Coupe: 'Robe élégante',
      Finition: 'Couture soignée',
      Délai: '7 à 10 jours',
    },
    isNew: false,
  },
  {
    id: 104,
    name: 'Robe Collection ' + 5,
    category: 'robes',
    categoryLabel: 'Robe',
    image: '/robes/36ccf997b0e1c35e259588713cf1a1ec.jpg',
    price: '40 000 FCFA',
    rating: 4.8,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Robe de haute qualité avec un design unique.',
    specs: {
      Matière: 'Wax / Dentelle / Pagne',
      Coupe: 'Robe élégante',
      Finition: 'Couture soignée',
      Délai: '7 à 10 jours',
    },
    isNew: false,
  },
  {
    id: 105,
    name: 'Robe Collection ' + 6,
    category: 'robes',
    categoryLabel: 'Robe',
    image: '/robes/38c2c24aa25dbc035730442cb5981ff9.jpg',
    price: '40 000 FCFA',
    rating: 4.8,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Robe de haute qualité avec un design unique.',
    specs: {
      Matière: 'Wax / Dentelle / Pagne',
      Coupe: 'Robe élégante',
      Finition: 'Couture soignée',
      Délai: '7 à 10 jours',
    },
    isNew: false,
  },
  {
    id: 106,
    name: 'Robe Collection ' + 7,
    category: 'robes',
    categoryLabel: 'Robe',
    image: '/robes/445bec7014da28aa5d98cc66bc2f5d5d.jpg',
    price: '40 000 FCFA',
    rating: 4.8,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Robe de haute qualité avec un design unique.',
    specs: {
      Matière: 'Wax / Dentelle / Pagne',
      Coupe: 'Robe élégante',
      Finition: 'Couture soignée',
      Délai: '7 à 10 jours',
    },
    isNew: false,
  },
  {
    id: 107,
    name: 'Robe Collection ' + 8,
    category: 'robes',
    categoryLabel: 'Robe',
    image: '/robes/53763e96dc359dfd3937da29822972e6.jpg',
    price: '40 000 FCFA',
    rating: 4.8,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Robe de haute qualité avec un design unique.',
    specs: {
      Matière: 'Wax / Dentelle / Pagne',
      Coupe: 'Robe élégante',
      Finition: 'Couture soignée',
      Délai: '7 à 10 jours',
    },
    isNew: false,
  },
  {
    id: 108,
    name: 'Robe Collection ' + 9,
    category: 'robes',
    categoryLabel: 'Robe',
    image: '/robes/56e6927101fba15146dd76df224a8103.jpg',
    price: '40 000 FCFA',
    rating: 4.8,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Robe de haute qualité avec un design unique.',
    specs: {
      Matière: 'Wax / Dentelle / Pagne',
      Coupe: 'Robe élégante',
      Finition: 'Couture soignée',
      Délai: '7 à 10 jours',
    },
    isNew: false,
  },
  {
    id: 109,
    name: 'Robe Collection ' + 10,
    category: 'robes',
    categoryLabel: 'Robe',
    image: '/robes/56e83fc5bbebbd26d08595afff2cf906.jpg',
    price: '40 000 FCFA',
    rating: 4.8,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Robe de haute qualité avec un design unique.',
    specs: {
      Matière: 'Wax / Dentelle / Pagne',
      Coupe: 'Robe élégante',
      Finition: 'Couture soignée',
      Délai: '7 à 10 jours',
    },
    isNew: false,
  },
  {
    id: 110,
    name: 'Robe Collection ' + 11,
    category: 'robes',
    categoryLabel: 'Robe',
    image: '/robes/584e864f22ea283447e9d2842744db4c.jpg',
    price: '40 000 FCFA',
    rating: 4.8,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Robe de haute qualité avec un design unique.',
    specs: {
      Matière: 'Wax / Dentelle / Pagne',
      Coupe: 'Robe élégante',
      Finition: 'Couture soignée',
      Délai: '7 à 10 jours',
    },
    isNew: false,
  },
  {
    id: 111,
    name: 'Robe Collection ' + 12,
    category: 'robes',
    categoryLabel: 'Robe',
    image: '/robes/606f81a8a728ce2f0d3d2f3d2359e5d9.jpg',
    price: '40 000 FCFA',
    rating: 4.8,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Robe de haute qualité avec un design unique.',
    specs: {
      Matière: 'Wax / Dentelle / Pagne',
      Coupe: 'Robe élégante',
      Finition: 'Couture soignée',
      Délai: '7 à 10 jours',
    },
    isNew: false,
  },
  {
    id: 112,
    name: 'Robe Collection ' + 13,
    category: 'robes',
    categoryLabel: 'Robe',
    image: '/robes/614e513671e5bbbe588ecc2d01e7c7f9.jpg',
    price: '40 000 FCFA',
    rating: 4.8,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Robe de haute qualité avec un design unique.',
    specs: {
      Matière: 'Wax / Dentelle / Pagne',
      Coupe: 'Robe élégante',
      Finition: 'Couture soignée',
      Délai: '7 à 10 jours',
    },
    isNew: false,
  },
  {
    id: 113,
    name: 'Robe Collection ' + 14,
    category: 'robes',
    categoryLabel: 'Robe',
    image: '/robes/65193deae5db0375fa1e762beb01726f.jpg',
    price: '40 000 FCFA',
    rating: 4.8,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Robe de haute qualité avec un design unique.',
    specs: {
      Matière: 'Wax / Dentelle / Pagne',
      Coupe: 'Robe élégante',
      Finition: 'Couture soignée',
      Délai: '7 à 10 jours',
    },
    isNew: false,
  },
  {
    id: 114,
    name: 'Robe Collection ' + 15,
    category: 'robes',
    categoryLabel: 'Robe',
    image: '/robes/6b888e72597568fac69e372812da6f7e.jpg',
    price: '40 000 FCFA',
    rating: 4.8,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Robe de haute qualité avec un design unique.',
    specs: {
      Matière: 'Wax / Dentelle / Pagne',
      Coupe: 'Robe élégante',
      Finition: 'Couture soignée',
      Délai: '7 à 10 jours',
    },
    isNew: false,
  },
  {
    id: 115,
    name: 'Robe Collection ' + 16,
    category: 'robes',
    categoryLabel: 'Robe',
    image: '/robes/7278ed6bf04d5b8766a05971dba4f14e.jpg',
    price: '40 000 FCFA',
    rating: 4.8,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Robe de haute qualité avec un design unique.',
    specs: {
      Matière: 'Wax / Dentelle / Pagne',
      Coupe: 'Robe élégante',
      Finition: 'Couture soignée',
      Délai: '7 à 10 jours',
    },
    isNew: false,
  },
  {
    id: 116,
    name: 'Robe Collection ' + 17,
    category: 'robes',
    categoryLabel: 'Robe',
    image: '/robes/7f4c42cfcf532b014c5415ed59c2fc68.jpg',
    price: '40 000 FCFA',
    rating: 4.8,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Robe de haute qualité avec un design unique.',
    specs: {
      Matière: 'Wax / Dentelle / Pagne',
      Coupe: 'Robe élégante',
      Finition: 'Couture soignée',
      Délai: '7 à 10 jours',
    },
    isNew: false,
  },
  {
    id: 117,
    name: 'Robe Collection ' + 18,
    category: 'robes',
    categoryLabel: 'Robe',
    image: '/robes/833c0543c0b725de4acd06cd84f9f949.jpg',
    price: '40 000 FCFA',
    rating: 4.8,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Robe de haute qualité avec un design unique.',
    specs: {
      Matière: 'Wax / Dentelle / Pagne',
      Coupe: 'Robe élégante',
      Finition: 'Couture soignée',
      Délai: '7 à 10 jours',
    },
    isNew: false,
  },
  {
    id: 118,
    name: 'Robe Collection ' + 19,
    category: 'robes',
    categoryLabel: 'Robe',
    image: '/robes/8407f01c2767e71c50b956f468bab757.jpg',
    price: '40 000 FCFA',
    rating: 4.8,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Robe de haute qualité avec un design unique.',
    specs: {
      Matière: 'Wax / Dentelle / Pagne',
      Coupe: 'Robe élégante',
      Finition: 'Couture soignée',
      Délai: '7 à 10 jours',
    },
    isNew: false,
  },
  {
    id: 119,
    name: 'Robe Collection ' + 20,
    category: 'robes',
    categoryLabel: 'Robe',
    image: '/robes/86598a31f59e9ec212ae0f75d3a3d643.jpg',
    price: '40 000 FCFA',
    rating: 4.8,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Robe de haute qualité avec un design unique.',
    specs: {
      Matière: 'Wax / Dentelle / Pagne',
      Coupe: 'Robe élégante',
      Finition: 'Couture soignée',
      Délai: '7 à 10 jours',
    },
    isNew: false,
  },
  {
    id: 120,
    name: 'Robe Collection ' + 21,
    category: 'robes',
    categoryLabel: 'Robe',
    image: '/robes/8d6f7386c975c1809156493e91bfb01b.jpg',
    price: '40 000 FCFA',
    rating: 4.8,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Robe de haute qualité avec un design unique.',
    specs: {
      Matière: 'Wax / Dentelle / Pagne',
      Coupe: 'Robe élégante',
      Finition: 'Couture soignée',
      Délai: '7 à 10 jours',
    },
    isNew: false,
  },
  {
    id: 121,
    name: 'Robe Collection ' + 22,
    category: 'robes',
    categoryLabel: 'Robe',
    image: '/robes/8ddf11a049950d2a6758531ba7e26468.jpg',
    price: '40 000 FCFA',
    rating: 4.8,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Robe de haute qualité avec un design unique.',
    specs: {
      Matière: 'Wax / Dentelle / Pagne',
      Coupe: 'Robe élégante',
      Finition: 'Couture soignée',
      Délai: '7 à 10 jours',
    },
    isNew: false,
  },
  {
    id: 122,
    name: 'Robe Collection ' + 23,
    category: 'robes',
    categoryLabel: 'Robe',
    image: '/robes/906dec0331e7e584485af08d065055bd.jpg',
    price: '40 000 FCFA',
    rating: 4.8,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Robe de haute qualité avec un design unique.',
    specs: {
      Matière: 'Wax / Dentelle / Pagne',
      Coupe: 'Robe élégante',
      Finition: 'Couture soignée',
      Délai: '7 à 10 jours',
    },
    isNew: false,
  },
  {
    id: 123,
    name: 'Robe Collection ' + 24,
    category: 'robes',
    categoryLabel: 'Robe',
    image: '/robes/973504ac882a02470746c903bf4e183f.jpg',
    price: '40 000 FCFA',
    rating: 4.8,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Robe de haute qualité avec un design unique.',
    specs: {
      Matière: 'Wax / Dentelle / Pagne',
      Coupe: 'Robe élégante',
      Finition: 'Couture soignée',
      Délai: '7 à 10 jours',
    },
    isNew: false,
  },
  {
    id: 124,
    name: 'Robe Collection ' + 25,
    category: 'robes',
    categoryLabel: 'Robe',
    image: '/robes/a210f3bfb1c3b31431d3078728435518.jpg',
    price: '40 000 FCFA',
    rating: 4.8,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Robe de haute qualité avec un design unique.',
    specs: {
      Matière: 'Wax / Dentelle / Pagne',
      Coupe: 'Robe élégante',
      Finition: 'Couture soignée',
      Délai: '7 à 10 jours',
    },
    isNew: false,
  },
  {
    id: 125,
    name: 'Robe Collection ' + 26,
    category: 'robes',
    categoryLabel: 'Robe',
    image: '/robes/a4d1613c37311bba4a9bc0513cbb7522.jpg',
    price: '40 000 FCFA',
    rating: 4.8,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Robe de haute qualité avec un design unique.',
    specs: {
      Matière: 'Wax / Dentelle / Pagne',
      Coupe: 'Robe élégante',
      Finition: 'Couture soignée',
      Délai: '7 à 10 jours',
    },
    isNew: false,
  },
  {
    id: 126,
    name: 'Robe Collection ' + 27,
    category: 'robes',
    categoryLabel: 'Robe',
    image: '/robes/a6ccaa85d08666e6f148ec038364cfed.jpg',
    price: '40 000 FCFA',
    rating: 4.8,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Robe de haute qualité avec un design unique.',
    specs: {
      Matière: 'Wax / Dentelle / Pagne',
      Coupe: 'Robe élégante',
      Finition: 'Couture soignée',
      Délai: '7 à 10 jours',
    },
    isNew: false,
  },
  {
    id: 127,
    name: 'Robe Collection ' + 28,
    category: 'robes',
    categoryLabel: 'Robe',
    image: '/robes/aa563cc42a4fb2c88d7083f99e1f93ae.jpg',
    price: '40 000 FCFA',
    rating: 4.8,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Robe de haute qualité avec un design unique.',
    specs: {
      Matière: 'Wax / Dentelle / Pagne',
      Coupe: 'Robe élégante',
      Finition: 'Couture soignée',
      Délai: '7 à 10 jours',
    },
    isNew: false,
  },
  {
    id: 128,
    name: 'Robe Collection ' + 29,
    category: 'robes',
    categoryLabel: 'Robe',
    image: '/robes/ade7bee0cef17d5332b1227fe90d9133.jpg',
    price: '40 000 FCFA',
    rating: 4.8,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Robe de haute qualité avec un design unique.',
    specs: {
      Matière: 'Wax / Dentelle / Pagne',
      Coupe: 'Robe élégante',
      Finition: 'Couture soignée',
      Délai: '7 à 10 jours',
    },
    isNew: false,
  },
  {
    id: 129,
    name: 'Robe Collection ' + 30,
    category: 'robes',
    categoryLabel: 'Robe',
    image: '/robes/ae7aeb1b868236d4fb0040d508713e88.jpg',
    price: '40 000 FCFA',
    rating: 4.8,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Robe de haute qualité avec un design unique.',
    specs: {
      Matière: 'Wax / Dentelle / Pagne',
      Coupe: 'Robe élégante',
      Finition: 'Couture soignée',
      Délai: '7 à 10 jours',
    },
    isNew: false,
  },
  {
    id: 130,
    name: 'Robe Collection ' + 31,
    category: 'robes',
    categoryLabel: 'Robe',
    image: '/robes/b039093f282d8ce0ac135535890e5c13.jpg',
    price: '40 000 FCFA',
    rating: 4.8,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Robe de haute qualité avec un design unique.',
    specs: {
      Matière: 'Wax / Dentelle / Pagne',
      Coupe: 'Robe élégante',
      Finition: 'Couture soignée',
      Délai: '7 à 10 jours',
    },
    isNew: false,
  },
  {
    id: 131,
    name: 'Robe Collection ' + 32,
    category: 'robes',
    categoryLabel: 'Robe',
    image: '/robes/c88f5fc13b0f2b05353cd8a91f393483.jpg',
    price: '40 000 FCFA',
    rating: 4.8,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Robe de haute qualité avec un design unique.',
    specs: {
      Matière: 'Wax / Dentelle / Pagne',
      Coupe: 'Robe élégante',
      Finition: 'Couture soignée',
      Délai: '7 à 10 jours',
    },
    isNew: false,
  },
  {
    id: 132,
    name: 'Robe Collection ' + 33,
    category: 'robes',
    categoryLabel: 'Robe',
    image: '/robes/ce0c8a9ba01e5642b9dff5fda4fe7d41.jpg',
    price: '40 000 FCFA',
    rating: 4.8,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Robe de haute qualité avec un design unique.',
    specs: {
      Matière: 'Wax / Dentelle / Pagne',
      Coupe: 'Robe élégante',
      Finition: 'Couture soignée',
      Délai: '7 à 10 jours',
    },
    isNew: false,
  },
  {
    id: 133,
    name: 'Robe Collection ' + 34,
    category: 'robes',
    categoryLabel: 'Robe',
    image: '/robes/d72ff9f6099dd20d362c36f8f268c75c.jpg',
    price: '40 000 FCFA',
    rating: 4.8,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Robe de haute qualité avec un design unique.',
    specs: {
      Matière: 'Wax / Dentelle / Pagne',
      Coupe: 'Robe élégante',
      Finition: 'Couture soignée',
      Délai: '7 à 10 jours',
    },
    isNew: false,
  },
  {
    id: 134,
    name: 'Robe Collection ' + 35,
    category: 'robes',
    categoryLabel: 'Robe',
    image: '/robes/e6ca6a4d113f47ca24b4f07d06a86aa0.jpg',
    price: '40 000 FCFA',
    rating: 4.8,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Robe de haute qualité avec un design unique.',
    specs: {
      Matière: 'Wax / Dentelle / Pagne',
      Coupe: 'Robe élégante',
      Finition: 'Couture soignée',
      Délai: '7 à 10 jours',
    },
    isNew: false,
  },
  {
    id: 135,
    name: 'Robe Collection ' + 36,
    category: 'robes',
    categoryLabel: 'Robe',
    image: '/robes/e7d00ba75d258bbb057163fee2b46479.jpg',
    price: '40 000 FCFA',
    rating: 4.8,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Robe de haute qualité avec un design unique.',
    specs: {
      Matière: 'Wax / Dentelle / Pagne',
      Coupe: 'Robe élégante',
      Finition: 'Couture soignée',
      Délai: '7 à 10 jours',
    },
    isNew: false,
  },
  {
    id: 136,
    name: 'Robe Collection ' + 37,
    category: 'robes',
    categoryLabel: 'Robe',
    image: '/robes/ebc54b1a8a3b3b9d24991e110950eeaf.jpg',
    price: '40 000 FCFA',
    rating: 4.8,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Robe de haute qualité avec un design unique.',
    specs: {
      Matière: 'Wax / Dentelle / Pagne',
      Coupe: 'Robe élégante',
      Finition: 'Couture soignée',
      Délai: '7 à 10 jours',
    },
    isNew: false,
  },
  {
    id: 137,
    name: 'Robe Collection ' + 38,
    category: 'robes',
    categoryLabel: 'Robe',
    image: '/robes/ef5496513dd7d37fabf9f64006fc92b0.jpg',
    price: '40 000 FCFA',
    rating: 4.8,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Robe de haute qualité avec un design unique.',
    specs: {
      Matière: 'Wax / Dentelle / Pagne',
      Coupe: 'Robe élégante',
      Finition: 'Couture soignée',
      Délai: '7 à 10 jours',
    },
    isNew: false,
  },
  {
    id: 138,
    name: 'Robe Collection ' + 39,
    category: 'robes',
    categoryLabel: 'Robe',
    image: '/robes/f3209809f288840765448194e3e6e6bb.jpg',
    price: '40 000 FCFA',
    rating: 4.8,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Robe de haute qualité avec un design unique.',
    specs: {
      Matière: 'Wax / Dentelle / Pagne',
      Coupe: 'Robe élégante',
      Finition: 'Couture soignée',
      Délai: '7 à 10 jours',
    },
    isNew: false,
  },
  {
    id: 139,
    name: 'Robe Collection ' + 40,
    category: 'robes',
    categoryLabel: 'Robe',
    image: '/robes/f670aa75101ef3930cf958b4678d448d.jpg',
    price: '40 000 FCFA',
    rating: 4.8,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Robe de haute qualité avec un design unique.',
    specs: {
      Matière: 'Wax / Dentelle / Pagne',
      Coupe: 'Robe élégante',
      Finition: 'Couture soignée',
      Délai: '7 à 10 jours',
    },
    isNew: false,
  },
  {
    id: 140,
    name: 'Robe Collection ' + 41,
    category: 'robes',
    categoryLabel: 'Robe',
    image: '/robes/f672d762189b2413b0baf7ac4d895759.jpg',
    price: '40 000 FCFA',
    rating: 4.8,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Robe de haute qualité avec un design unique.',
    specs: {
      Matière: 'Wax / Dentelle / Pagne',
      Coupe: 'Robe élégante',
      Finition: 'Couture soignée',
      Délai: '7 à 10 jours',
    },
    isNew: false,
  },
  {
    id: 141,
    name: 'Robe Collection ' + 42,
    category: 'robes',
    categoryLabel: 'Robe',
    image: '/robes/fac41bf6c13d133de83fc592e31be3ec.jpg',
    price: '40 000 FCFA',
    rating: 4.8,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Robe de haute qualité avec un design unique.',
    specs: {
      Matière: 'Wax / Dentelle / Pagne',
      Coupe: 'Robe élégante',
      Finition: 'Couture soignée',
      Délai: '7 à 10 jours',
    },
    isNew: false,
  },
  {
    id: 142,
    name: 'Robe Collection ' + 43,
    category: 'robes',
    categoryLabel: 'Robe',
    image: '/robes/fd74e094a139684641f0499244753099.jpg',
    price: '40 000 FCFA',
    rating: 4.8,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Robe de haute qualité avec un design unique.',
    specs: {
      Matière: 'Wax / Dentelle / Pagne',
      Coupe: 'Robe élégante',
      Finition: 'Couture soignée',
      Délai: '7 à 10 jours',
    },
    isNew: false,
  },
  {
    id: 143,
    name: 'Robe Collection ' + 44,
    category: 'robes',
    categoryLabel: 'Robe',
    image: '/robes/ff85c8b1ef291412edb70344b56a1209.jpg',
    price: '40 000 FCFA',
    rating: 4.8,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Robe de haute qualité avec un design unique.',
    specs: {
      Matière: 'Wax / Dentelle / Pagne',
      Coupe: 'Robe élégante',
      Finition: 'Couture soignée',
      Délai: '7 à 10 jours',
    },
    isNew: false,
  },
  {
    id: 144,
    name: 'Robe Collection ' + 45,
    category: 'robes',
    categoryLabel: 'Robe',
    image: '/robes/téléchargement (1).png',
    price: '40 000 FCFA',
    rating: 4.8,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Robe de haute qualité avec un design unique.',
    specs: {
      Matière: 'Wax / Dentelle / Pagne',
      Coupe: 'Robe élégante',
      Finition: 'Couture soignée',
      Délai: '7 à 10 jours',
    },
    isNew: false,
  },
  {
    id: 200,
    name: 'Ensemble Élégance ' + 1,
    category: 'ensembles',
    categoryLabel: 'Ensemble',
    image: '/ensembles/0f1ec675ab80441ecf41e14f321b2359.jpg',
    price: '45 000 FCFA',
    rating: 4.7,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Ensemble magnifique avec un design unique.',
    specs: {
      Matière: 'Wax / Dentelle / Pagne',
      Coupe: 'Ensemble élégant',
      Finition: 'Couture soignée',
      Délai: '7 à 10 jours',
    },
    isNew: false,
  },
  {
    id: 201,
    name: 'Ensemble Élégance ' + 2,
    category: 'ensembles',
    categoryLabel: 'Ensemble',
    image: '/ensembles/3aee58539269203388bd5bbb7aa0e69d.jpg',
    price: '45 000 FCFA',
    rating: 4.7,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Ensemble magnifique avec un design unique.',
    specs: {
      Matière: 'Wax / Dentelle / Pagne',
      Coupe: 'Ensemble élégant',
      Finition: 'Couture soignée',
      Délai: '7 à 10 jours',
    },
    isNew: false,
  },
  {
    id: 202,
    name: 'Ensemble Élégance ' + 3,
    category: 'ensembles',
    categoryLabel: 'Ensemble',
    image: '/ensembles/5718dca4132df9bd7ddae1fc052b8049.jpg',
    price: '45 000 FCFA',
    rating: 4.7,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Ensemble magnifique avec un design unique.',
    specs: {
      Matière: 'Wax / Dentelle / Pagne',
      Coupe: 'Ensemble élégant',
      Finition: 'Couture soignée',
      Délai: '7 à 10 jours',
    },
    isNew: false,
  },
  {
    id: 203,
    name: 'Ensemble Élégance ' + 4,
    category: 'ensembles',
    categoryLabel: 'Ensemble',
    image: '/ensembles/5877d3a76e0c469d11519c1a5c2ea880.jpg',
    price: '45 000 FCFA',
    rating: 4.7,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Ensemble magnifique avec un design unique.',
    specs: {
      Matière: 'Wax / Dentelle / Pagne',
      Coupe: 'Ensemble élégant',
      Finition: 'Couture soignée',
      Délai: '7 à 10 jours',
    },
    isNew: false,
  },
  {
    id: 204,
    name: 'Ensemble Élégance ' + 5,
    category: 'ensembles',
    categoryLabel: 'Ensemble',
    image: '/ensembles/6332c76d1e3f226bec5dcf47a0450fc4.jpg',
    price: '45 000 FCFA',
    rating: 4.7,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Ensemble magnifique avec un design unique.',
    specs: {
      Matière: 'Wax / Dentelle / Pagne',
      Coupe: 'Ensemble élégant',
      Finition: 'Couture soignée',
      Délai: '7 à 10 jours',
    },
    isNew: false,
  },
  {
    id: 205,
    name: 'Ensemble Élégance ' + 6,
    category: 'ensembles',
    categoryLabel: 'Ensemble',
    image: '/ensembles/75979322daf0a0914476e0e42942d090.jpg',
    price: '45 000 FCFA',
    rating: 4.7,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Ensemble magnifique avec un design unique.',
    specs: {
      Matière: 'Wax / Dentelle / Pagne',
      Coupe: 'Ensemble élégant',
      Finition: 'Couture soignée',
      Délai: '7 à 10 jours',
    },
    isNew: false,
  },
  {
    id: 206,
    name: 'Ensemble Élégance ' + 7,
    category: 'ensembles',
    categoryLabel: 'Ensemble',
    image: '/ensembles/7cdf652e8561f3603d6587355a52e6ee.jpg',
    price: '45 000 FCFA',
    rating: 4.7,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Ensemble magnifique avec un design unique.',
    specs: {
      Matière: 'Wax / Dentelle / Pagne',
      Coupe: 'Ensemble élégant',
      Finition: 'Couture soignée',
      Délai: '7 à 10 jours',
    },
    isNew: false,
  },
  {
    id: 207,
    name: 'Ensemble Élégance ' + 8,
    category: 'ensembles',
    categoryLabel: 'Ensemble',
    image: '/ensembles/906c7a9b8b62ae53ab64740c94f24cf4.jpg',
    price: '45 000 FCFA',
    rating: 4.7,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Ensemble magnifique avec un design unique.',
    specs: {
      Matière: 'Wax / Dentelle / Pagne',
      Coupe: 'Ensemble élégant',
      Finition: 'Couture soignée',
      Délai: '7 à 10 jours',
    },
    isNew: false,
  },
  {
    id: 208,
    name: 'Ensemble Élégance ' + 9,
    category: 'ensembles',
    categoryLabel: 'Ensemble',
    image: '/ensembles/9259ce32615fdd752e84a2cd386a1df4.jpg',
    price: '45 000 FCFA',
    rating: 4.7,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Ensemble magnifique avec un design unique.',
    specs: {
      Matière: 'Wax / Dentelle / Pagne',
      Coupe: 'Ensemble élégant',
      Finition: 'Couture soignée',
      Délai: '7 à 10 jours',
    },
    isNew: false,
  },
  {
    id: 209,
    name: 'Ensemble Élégance ' + 10,
    category: 'ensembles',
    categoryLabel: 'Ensemble',
    image: '/ensembles/94b94294f716b1f343076f543503bc79.jpg',
    price: '45 000 FCFA',
    rating: 4.7,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Ensemble magnifique avec un design unique.',
    specs: {
      Matière: 'Wax / Dentelle / Pagne',
      Coupe: 'Ensemble élégant',
      Finition: 'Couture soignée',
      Délai: '7 à 10 jours',
    },
    isNew: false,
  },
  {
    id: 210,
    name: 'Ensemble Élégance ' + 11,
    category: 'ensembles',
    categoryLabel: 'Ensemble',
    image: '/ensembles/a070065f519daa8a8a48e4165b618239.jpg',
    price: '45 000 FCFA',
    rating: 4.7,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Ensemble magnifique avec un design unique.',
    specs: {
      Matière: 'Wax / Dentelle / Pagne',
      Coupe: 'Ensemble élégant',
      Finition: 'Couture soignée',
      Délai: '7 à 10 jours',
    },
    isNew: false,
  },
  {
    id: 211,
    name: 'Ensemble Élégance ' + 12,
    category: 'ensembles',
    categoryLabel: 'Ensemble',
    image: '/ensembles/a3011a680e8a86630c725ed9c7c75c43.jpg',
    price: '45 000 FCFA',
    rating: 4.7,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Ensemble magnifique avec un design unique.',
    specs: {
      Matière: 'Wax / Dentelle / Pagne',
      Coupe: 'Ensemble élégant',
      Finition: 'Couture soignée',
      Délai: '7 à 10 jours',
    },
    isNew: false,
  },
  {
    id: 212,
    name: 'Ensemble Élégance ' + 13,
    category: 'ensembles',
    categoryLabel: 'Ensemble',
    image: '/ensembles/a448ef3d62fcaa6997dd5739e3ec7f28.jpg',
    price: '45 000 FCFA',
    rating: 4.7,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Ensemble magnifique avec un design unique.',
    specs: {
      Matière: 'Wax / Dentelle / Pagne',
      Coupe: 'Ensemble élégant',
      Finition: 'Couture soignée',
      Délai: '7 à 10 jours',
    },
    isNew: false,
  },
  {
    id: 213,
    name: 'Ensemble Élégance ' + 14,
    category: 'ensembles',
    categoryLabel: 'Ensemble',
    image: '/ensembles/b3fc6744540c57ebdcb792d42fad0347.jpg',
    price: '45 000 FCFA',
    rating: 4.7,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Ensemble magnifique avec un design unique.',
    specs: {
      Matière: 'Wax / Dentelle / Pagne',
      Coupe: 'Ensemble élégant',
      Finition: 'Couture soignée',
      Délai: '7 à 10 jours',
    },
    isNew: false,
  },
  {
    id: 214,
    name: 'Ensemble Élégance ' + 15,
    category: 'ensembles',
    categoryLabel: 'Ensemble',
    image: '/ensembles/baa6ed3f3442d152c201c72714d454b4.jpg',
    price: '45 000 FCFA',
    rating: 4.7,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Ensemble magnifique avec un design unique.',
    specs: {
      Matière: 'Wax / Dentelle / Pagne',
      Coupe: 'Ensemble élégant',
      Finition: 'Couture soignée',
      Délai: '7 à 10 jours',
    },
    isNew: false,
  },
  {
    id: 215,
    name: 'Ensemble Élégance ' + 16,
    category: 'ensembles',
    categoryLabel: 'Ensemble',
    image: '/ensembles/e47c4a79346903c357c2287128e44bec.jpg',
    price: '45 000 FCFA',
    rating: 4.7,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Ensemble magnifique avec un design unique.',
    specs: {
      Matière: 'Wax / Dentelle / Pagne',
      Coupe: 'Ensemble élégant',
      Finition: 'Couture soignée',
      Délai: '7 à 10 jours',
    },
    isNew: false,
  },
  {
    id: 216,
    name: 'Ensemble Élégance ' + 17,
    category: 'ensembles',
    categoryLabel: 'Ensemble',
    image: '/ensembles/eaa56e7630f3fa0527b8447144ba00db.jpg',
    price: '45 000 FCFA',
    rating: 4.7,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Ensemble magnifique avec un design unique.',
    specs: {
      Matière: 'Wax / Dentelle / Pagne',
      Coupe: 'Ensemble élégant',
      Finition: 'Couture soignée',
      Délai: '7 à 10 jours',
    },
    isNew: false,
  },
  {
    id: 217,
    name: 'Ensemble Élégance ' + 18,
    category: 'ensembles',
    categoryLabel: 'Ensemble',
    image: '/ensembles/ed478416045e1e1d6f66d066bf3d577d.jpg',
    price: '45 000 FCFA',
    rating: 4.7,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Ensemble magnifique avec un design unique.',
    specs: {
      Matière: 'Wax / Dentelle / Pagne',
      Coupe: 'Ensemble élégant',
      Finition: 'Couture soignée',
      Délai: '7 à 10 jours',
    },
    isNew: false,
  },
  {
    id: 218,
    name: 'Ensemble Élégance ' + 19,
    category: 'ensembles',
    categoryLabel: 'Ensemble',
    image: '/ensembles/ee09e0ac548accc71de21bf838cf5732.jpg',
    price: '45 000 FCFA',
    rating: 4.7,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Ensemble magnifique avec un design unique.',
    specs: {
      Matière: 'Wax / Dentelle / Pagne',
      Coupe: 'Ensemble élégant',
      Finition: 'Couture soignée',
      Délai: '7 à 10 jours',
    },
    isNew: false,
  },
  {
    id: 219,
    name: 'Ensemble Élégance ' + 20,
    category: 'ensembles',
    categoryLabel: 'Ensemble',
    image: '/ensembles/f1129df5ff9704bb5f2f83b495070bc8.jpg',
    price: '45 000 FCFA',
    rating: 4.7,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Ensemble magnifique avec un design unique.',
    specs: {
      Matière: 'Wax / Dentelle / Pagne',
      Coupe: 'Ensemble élégant',
      Finition: 'Couture soignée',
      Délai: '7 à 10 jours',
    },
    isNew: false,
  },
  {
    id: 300,
    name: 'Jupe Tendance ' + 1,
    category: 'jupes',
    categoryLabel: 'Jupe',
    image: '/jupes/05884677d319fb9abc62d5f5a0bb94e9.jpg',
    price: '25 000 FCFA',
    rating: 4.6,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Jupe élégante au design raffiné, parfaite pour toutes les occasions.',
    specs: {
      Matière: 'Wax / Coton / Dentelle',
      Coupe: 'Jupe ajustée',
      Finition: 'Couture soignée',
      Délai: '5 à 7 jours',
    },
    isNew: false,
  },
  {
    id: 301,
    name: 'Jupe Tendance ' + 2,
    category: 'jupes',
    categoryLabel: 'Jupe',
    image: '/jupes/2742614b09970cfe124cba50a0769faa.jpg',
    price: '25 000 FCFA',
    rating: 4.6,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Jupe élégante au design raffiné, parfaite pour toutes les occasions.',
    specs: {
      Matière: 'Wax / Coton / Dentelle',
      Coupe: 'Jupe ajustée',
      Finition: 'Couture soignée',
      Délai: '5 à 7 jours',
    },
    isNew: false,
  },
  {
    id: 302,
    name: 'Jupe Tendance ' + 3,
    category: 'jupes',
    categoryLabel: 'Jupe',
    image: '/jupes/2abda6eaae32bdbd309a807ae2cff39e.jpg',
    price: '25 000 FCFA',
    rating: 4.6,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Jupe élégante au design raffiné, parfaite pour toutes les occasions.',
    specs: {
      Matière: 'Wax / Coton / Dentelle',
      Coupe: 'Jupe ajustée',
      Finition: 'Couture soignée',
      Délai: '5 à 7 jours',
    },
    isNew: false,
  },
  {
    id: 303,
    name: 'Jupe Tendance ' + 4,
    category: 'jupes',
    categoryLabel: 'Jupe',
    image: '/jupes/32dcc8777687018066c32942ae747ee2.jpg',
    price: '25 000 FCFA',
    rating: 4.6,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Jupe élégante au design raffiné, parfaite pour toutes les occasions.',
    specs: {
      Matière: 'Wax / Coton / Dentelle',
      Coupe: 'Jupe ajustée',
      Finition: 'Couture soignée',
      Délai: '5 à 7 jours',
    },
    isNew: false,
  },
  {
    id: 304,
    name: 'Jupe Tendance ' + 5,
    category: 'jupes',
    categoryLabel: 'Jupe',
    image: '/jupes/3462a322707a80a7271adcc9c411e30c.jpg',
    price: '25 000 FCFA',
    rating: 4.6,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Jupe élégante au design raffiné, parfaite pour toutes les occasions.',
    specs: {
      Matière: 'Wax / Coton / Dentelle',
      Coupe: 'Jupe ajustée',
      Finition: 'Couture soignée',
      Délai: '5 à 7 jours',
    },
    isNew: false,
  },
  {
    id: 305,
    name: 'Jupe Tendance ' + 6,
    category: 'jupes',
    categoryLabel: 'Jupe',
    image: '/jupes/3787044fcdd228086146410b8c3ccbd3.jpg',
    price: '25 000 FCFA',
    rating: 4.6,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Jupe élégante au design raffiné, parfaite pour toutes les occasions.',
    specs: {
      Matière: 'Wax / Coton / Dentelle',
      Coupe: 'Jupe ajustée',
      Finition: 'Couture soignée',
      Délai: '5 à 7 jours',
    },
    isNew: false,
  },
  {
    id: 306,
    name: 'Jupe Tendance ' + 7,
    category: 'jupes',
    categoryLabel: 'Jupe',
    image: '/jupes/4e6a870124bf5198cd32a2c432eb3605.jpg',
    price: '25 000 FCFA',
    rating: 4.6,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Jupe élégante au design raffiné, parfaite pour toutes les occasions.',
    specs: {
      Matière: 'Wax / Coton / Dentelle',
      Coupe: 'Jupe ajustée',
      Finition: 'Couture soignée',
      Délai: '5 à 7 jours',
    },
    isNew: false,
  },
  {
    id: 307,
    name: 'Jupe Tendance ' + 8,
    category: 'jupes',
    categoryLabel: 'Jupe',
    image: '/jupes/60e1afa113dbad89c180781347effa12.jpg',
    price: '25 000 FCFA',
    rating: 4.6,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Jupe élégante au design raffiné, parfaite pour toutes les occasions.',
    specs: {
      Matière: 'Wax / Coton / Dentelle',
      Coupe: 'Jupe ajustée',
      Finition: 'Couture soignée',
      Délai: '5 à 7 jours',
    },
    isNew: false,
  },
  {
    id: 308,
    name: 'Jupe Tendance ' + 9,
    category: 'jupes',
    categoryLabel: 'Jupe',
    image: '/jupes/629b1e3b138873d081a241d8af1f0f43.jpg',
    price: '25 000 FCFA',
    rating: 4.6,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Jupe élégante au design raffiné, parfaite pour toutes les occasions.',
    specs: {
      Matière: 'Wax / Coton / Dentelle',
      Coupe: 'Jupe ajustée',
      Finition: 'Couture soignée',
      Délai: '5 à 7 jours',
    },
    isNew: false,
  },
  {
    id: 309,
    name: 'Jupe Tendance ' + 10,
    category: 'jupes',
    categoryLabel: 'Jupe',
    image: '/jupes/71cb921119554ee188d60cc1ebe737e7.jpg',
    price: '25 000 FCFA',
    rating: 4.6,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Jupe élégante au design raffiné, parfaite pour toutes les occasions.',
    specs: {
      Matière: 'Wax / Coton / Dentelle',
      Coupe: 'Jupe ajustée',
      Finition: 'Couture soignée',
      Délai: '5 à 7 jours',
    },
    isNew: false,
  },
  {
    id: 310,
    name: 'Jupe Tendance ' + 11,
    category: 'jupes',
    categoryLabel: 'Jupe',
    image: '/jupes/790d00ae24a18622e151c8e83b18515a.jpg',
    price: '25 000 FCFA',
    rating: 4.6,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Jupe élégante au design raffiné, parfaite pour toutes les occasions.',
    specs: {
      Matière: 'Wax / Coton / Dentelle',
      Coupe: 'Jupe ajustée',
      Finition: 'Couture soignée',
      Délai: '5 à 7 jours',
    },
    isNew: false,
  },
  {
    id: 311,
    name: 'Jupe Tendance ' + 12,
    category: 'jupes',
    categoryLabel: 'Jupe',
    image: '/jupes/7c04dbaf445012e938f9dbf6fbd379ad.jpg',
    price: '25 000 FCFA',
    rating: 4.6,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Jupe élégante au design raffiné, parfaite pour toutes les occasions.',
    specs: {
      Matière: 'Wax / Coton / Dentelle',
      Coupe: 'Jupe ajustée',
      Finition: 'Couture soignée',
      Délai: '5 à 7 jours',
    },
    isNew: false,
  },
  {
    id: 312,
    name: 'Jupe Tendance ' + 13,
    category: 'jupes',
    categoryLabel: 'Jupe',
    image: '/jupes/a774359d1f18ded0cc9b8b75ec1ccdd4.jpg',
    price: '25 000 FCFA',
    rating: 4.6,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Jupe élégante au design raffiné, parfaite pour toutes les occasions.',
    specs: {
      Matière: 'Wax / Coton / Dentelle',
      Coupe: 'Jupe ajustée',
      Finition: 'Couture soignée',
      Délai: '5 à 7 jours',
    },
    isNew: false,
  },
  {
    id: 313,
    name: 'Jupe Tendance ' + 14,
    category: 'jupes',
    categoryLabel: 'Jupe',
    image: '/jupes/aa56b33524e44d46979fba807305a8cf.jpg',
    price: '25 000 FCFA',
    rating: 4.6,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Jupe élégante au design raffiné, parfaite pour toutes les occasions.',
    specs: {
      Matière: 'Wax / Coton / Dentelle',
      Coupe: 'Jupe ajustée',
      Finition: 'Couture soignée',
      Délai: '5 à 7 jours',
    },
    isNew: false,
  },
  {
    id: 314,
    name: 'Jupe Tendance ' + 15,
    category: 'jupes',
    categoryLabel: 'Jupe',
    image: '/jupes/ac283b9b10c6c20cb9c081540a79dd48.jpg',
    price: '25 000 FCFA',
    rating: 4.6,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Jupe élégante au design raffiné, parfaite pour toutes les occasions.',
    specs: {
      Matière: 'Wax / Coton / Dentelle',
      Coupe: 'Jupe ajustée',
      Finition: 'Couture soignée',
      Délai: '5 à 7 jours',
    },
    isNew: false,
  },
  {
    id: 315,
    name: 'Jupe Tendance ' + 16,
    category: 'jupes',
    categoryLabel: 'Jupe',
    image: '/jupes/b48b7601f9c8f8c6c2386f35a0bad4e4.jpg',
    price: '25 000 FCFA',
    rating: 4.6,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Jupe élégante au design raffiné, parfaite pour toutes les occasions.',
    specs: {
      Matière: 'Wax / Coton / Dentelle',
      Coupe: 'Jupe ajustée',
      Finition: 'Couture soignée',
      Délai: '5 à 7 jours',
    },
    isNew: false,
  },
  {
    id: 316,
    name: 'Jupe Tendance ' + 17,
    category: 'jupes',
    categoryLabel: 'Jupe',
    image: '/jupes/c872bc5060bb58eb077a8e2f664ec0bd.jpg',
    price: '25 000 FCFA',
    rating: 4.6,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Jupe élégante au design raffiné, parfaite pour toutes les occasions.',
    specs: {
      Matière: 'Wax / Coton / Dentelle',
      Coupe: 'Jupe ajustée',
      Finition: 'Couture soignée',
      Délai: '5 à 7 jours',
    },
    isNew: false,
  },
  {
    id: 317,
    name: 'Jupe Tendance ' + 18,
    category: 'jupes',
    categoryLabel: 'Jupe',
    image: '/jupes/d48345d990f13dd81bcf344e20792d42.jpg',
    price: '25 000 FCFA',
    rating: 4.6,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Jupe élégante au design raffiné, parfaite pour toutes les occasions.',
    specs: {
      Matière: 'Wax / Coton / Dentelle',
      Coupe: 'Jupe ajustée',
      Finition: 'Couture soignée',
      Délai: '5 à 7 jours',
    },
    isNew: false,
  },
  {
    id: 318,
    name: 'Jupe Tendance ' + 19,
    category: 'jupes',
    categoryLabel: 'Jupe',
    image: '/jupes/de29f6229f25588d01cce22335cc26b2.jpg',
    price: '25 000 FCFA',
    rating: 4.6,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Jupe élégante au design raffiné, parfaite pour toutes les occasions.',
    specs: {
      Matière: 'Wax / Coton / Dentelle',
      Coupe: 'Jupe ajustée',
      Finition: 'Couture soignée',
      Délai: '5 à 7 jours',
    },
    isNew: false,
  },
  {
    id: 319,
    name: 'Jupe Tendance ' + 20,
    category: 'jupes',
    categoryLabel: 'Jupe',
    image: '/jupes/e626fa61a652e33564dd7d280c2ad19e.jpg',
    price: '25 000 FCFA',
    rating: 4.6,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Jupe élégante au design raffiné, parfaite pour toutes les occasions.',
    specs: {
      Matière: 'Wax / Coton / Dentelle',
      Coupe: 'Jupe ajustée',
      Finition: 'Couture soignée',
      Délai: '5 à 7 jours',
    },
    isNew: false,
  },
  {
    id: 320,
    name: 'Jupe Tendance ' + 21,
    category: 'jupes',
    categoryLabel: 'Jupe',
    image: '/jupes/e9a00d5c8cd6d41a1ed4e72d4498c2d2.jpg',
    price: '25 000 FCFA',
    rating: 4.6,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Jupe élégante au design raffiné, parfaite pour toutes les occasions.',
    specs: {
      Matière: 'Wax / Coton / Dentelle',
      Coupe: 'Jupe ajustée',
      Finition: 'Couture soignée',
      Délai: '5 à 7 jours',
    },
    isNew: false,
  },
  {
    id: 321,
    name: 'Jupe Tendance ' + 22,
    category: 'jupes',
    categoryLabel: 'Jupe',
    image: '/jupes/f7be98533dde5599cc271efcd83ca041.jpg',
    price: '25 000 FCFA',
    rating: 4.6,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Jupe élégante au design raffiné, parfaite pour toutes les occasions.',
    specs: {
      Matière: 'Wax / Coton / Dentelle',
      Coupe: 'Jupe ajustée',
      Finition: 'Couture soignée',
      Délai: '5 à 7 jours',
    },
    isNew: false,
  },
  {
    id: 400,
    name: 'Boubou Prestige ' + 1,
    category: 'boubous',
    categoryLabel: 'Boubou',
    image: '/boubous/0303944f46c80dec512ced93cf6a2ce9.jpg',
    price: '55 000 FCFA',
    rating: 4.9,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Boubou ample et majestueux, idéal pour les grandes occasions.',
    specs: {
      Matière: 'Bazin / Soie / Wax',
      Coupe: 'Boubou ample',
      Finition: 'Broderie artisanale',
      Délai: '10 à 14 jours',
    },
    isNew: false,
  },
  {
    id: 401,
    name: 'Boubou Prestige ' + 2,
    category: 'boubous',
    categoryLabel: 'Boubou',
    image: '/boubous/18e32a58b949a5d15fc321c369f1eca8.jpg',
    price: '55 000 FCFA',
    rating: 4.9,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Boubou ample et majestueux, idéal pour les grandes occasions.',
    specs: {
      Matière: 'Bazin / Soie / Wax',
      Coupe: 'Boubou ample',
      Finition: 'Broderie artisanale',
      Délai: '10 à 14 jours',
    },
    isNew: false,
  },
  {
    id: 402,
    name: 'Boubou Prestige ' + 3,
    category: 'boubous',
    categoryLabel: 'Boubou',
    image: '/boubous/1a91f95ac7a29d07d662fa08d33c9e8d.jpg',
    price: '55 000 FCFA',
    rating: 4.9,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Boubou ample et majestueux, idéal pour les grandes occasions.',
    specs: {
      Matière: 'Bazin / Soie / Wax',
      Coupe: 'Boubou ample',
      Finition: 'Broderie artisanale',
      Délai: '10 à 14 jours',
    },
    isNew: false,
  },
  {
    id: 403,
    name: 'Boubou Prestige ' + 4,
    category: 'boubous',
    categoryLabel: 'Boubou',
    image: '/boubous/24167704edd0e9daf0602f5990b59dae.jpg',
    price: '55 000 FCFA',
    rating: 4.9,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Boubou ample et majestueux, idéal pour les grandes occasions.',
    specs: {
      Matière: 'Bazin / Soie / Wax',
      Coupe: 'Boubou ample',
      Finition: 'Broderie artisanale',
      Délai: '10 à 14 jours',
    },
    isNew: false,
  },
  {
    id: 404,
    name: 'Boubou Prestige ' + 5,
    category: 'boubous',
    categoryLabel: 'Boubou',
    image: '/boubous/280fde0d90a4f42529d5f9ce950f7c75.jpg',
    price: '55 000 FCFA',
    rating: 4.9,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Boubou ample et majestueux, idéal pour les grandes occasions.',
    specs: {
      Matière: 'Bazin / Soie / Wax',
      Coupe: 'Boubou ample',
      Finition: 'Broderie artisanale',
      Délai: '10 à 14 jours',
    },
    isNew: false,
  },
  {
    id: 405,
    name: 'Boubou Prestige ' + 6,
    category: 'boubous',
    categoryLabel: 'Boubou',
    image: '/boubous/36f054ad285feff9685efbeea9a3bf2c.jpg',
    price: '55 000 FCFA',
    rating: 4.9,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Boubou ample et majestueux, idéal pour les grandes occasions.',
    specs: {
      Matière: 'Bazin / Soie / Wax',
      Coupe: 'Boubou ample',
      Finition: 'Broderie artisanale',
      Délai: '10 à 14 jours',
    },
    isNew: false,
  },
  {
    id: 406,
    name: 'Boubou Prestige ' + 7,
    category: 'boubous',
    categoryLabel: 'Boubou',
    image: '/boubous/46778b7401a1d0c412c3e0a7ed351a52.jpg',
    price: '55 000 FCFA',
    rating: 4.9,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Boubou ample et majestueux, idéal pour les grandes occasions.',
    specs: {
      Matière: 'Bazin / Soie / Wax',
      Coupe: 'Boubou ample',
      Finition: 'Broderie artisanale',
      Délai: '10 à 14 jours',
    },
    isNew: false,
  },
  {
    id: 407,
    name: 'Boubou Prestige ' + 8,
    category: 'boubous',
    categoryLabel: 'Boubou',
    image: '/boubous/548ceb476526dc923f7636a42ea7f149.jpg',
    price: '55 000 FCFA',
    rating: 4.9,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Boubou ample et majestueux, idéal pour les grandes occasions.',
    specs: {
      Matière: 'Bazin / Soie / Wax',
      Coupe: 'Boubou ample',
      Finition: 'Broderie artisanale',
      Délai: '10 à 14 jours',
    },
    isNew: false,
  },
  {
    id: 408,
    name: 'Boubou Prestige ' + 9,
    category: 'boubous',
    categoryLabel: 'Boubou',
    image: '/boubous/548edbad263cfded93ba0d41cdfe7371.jpg',
    price: '55 000 FCFA',
    rating: 4.9,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Boubou ample et majestueux, idéal pour les grandes occasions.',
    specs: {
      Matière: 'Bazin / Soie / Wax',
      Coupe: 'Boubou ample',
      Finition: 'Broderie artisanale',
      Délai: '10 à 14 jours',
    },
    isNew: false,
  },
  {
    id: 409,
    name: 'Boubou Prestige ' + 10,
    category: 'boubous',
    categoryLabel: 'Boubou',
    image: '/boubous/5bd6b277deb17b67c195434973b06a52.jpg',
    price: '55 000 FCFA',
    rating: 4.9,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Boubou ample et majestueux, idéal pour les grandes occasions.',
    specs: {
      Matière: 'Bazin / Soie / Wax',
      Coupe: 'Boubou ample',
      Finition: 'Broderie artisanale',
      Délai: '10 à 14 jours',
    },
    isNew: false,
  },
  {
    id: 410,
    name: 'Boubou Prestige ' + 11,
    category: 'boubous',
    categoryLabel: 'Boubou',
    image: '/boubous/5d68112648c2ff860df427ab425a9c56.jpg',
    price: '55 000 FCFA',
    rating: 4.9,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Boubou ample et majestueux, idéal pour les grandes occasions.',
    specs: {
      Matière: 'Bazin / Soie / Wax',
      Coupe: 'Boubou ample',
      Finition: 'Broderie artisanale',
      Délai: '10 à 14 jours',
    },
    isNew: false,
  },
  {
    id: 411,
    name: 'Boubou Prestige ' + 12,
    category: 'boubous',
    categoryLabel: 'Boubou',
    image: '/boubous/5f21c0df20001f31e8677f0c7980882f.jpg',
    price: '55 000 FCFA',
    rating: 4.9,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Boubou ample et majestueux, idéal pour les grandes occasions.',
    specs: {
      Matière: 'Bazin / Soie / Wax',
      Coupe: 'Boubou ample',
      Finition: 'Broderie artisanale',
      Délai: '10 à 14 jours',
    },
    isNew: false,
  },
  {
    id: 412,
    name: 'Boubou Prestige ' + 13,
    category: 'boubous',
    categoryLabel: 'Boubou',
    image: '/boubous/80de7d9b2ada59a2b0fc7b1c10798b51.jpg',
    price: '55 000 FCFA',
    rating: 4.9,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Boubou ample et majestueux, idéal pour les grandes occasions.',
    specs: {
      Matière: 'Bazin / Soie / Wax',
      Coupe: 'Boubou ample',
      Finition: 'Broderie artisanale',
      Délai: '10 à 14 jours',
    },
    isNew: false,
  },
  {
    id: 413,
    name: 'Boubou Prestige ' + 14,
    category: 'boubous',
    categoryLabel: 'Boubou',
    image: '/boubous/85c645b8db20d592ecdc16ce5d5724f2.jpg',
    price: '55 000 FCFA',
    rating: 4.9,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Boubou ample et majestueux, idéal pour les grandes occasions.',
    specs: {
      Matière: 'Bazin / Soie / Wax',
      Coupe: 'Boubou ample',
      Finition: 'Broderie artisanale',
      Délai: '10 à 14 jours',
    },
    isNew: false,
  },
  {
    id: 414,
    name: 'Boubou Prestige ' + 15,
    category: 'boubous',
    categoryLabel: 'Boubou',
    image: '/boubous/a8a23b630c02f8016249cf0745126788.jpg',
    price: '55 000 FCFA',
    rating: 4.9,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Boubou ample et majestueux, idéal pour les grandes occasions.',
    specs: {
      Matière: 'Bazin / Soie / Wax',
      Coupe: 'Boubou ample',
      Finition: 'Broderie artisanale',
      Délai: '10 à 14 jours',
    },
    isNew: false,
  },
  {
    id: 415,
    name: 'Boubou Prestige ' + 16,
    category: 'boubous',
    categoryLabel: 'Boubou',
    image: '/boubous/ad4fa65befca587dcabf21a3d7b2c388.jpg',
    price: '55 000 FCFA',
    rating: 4.9,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Boubou ample et majestueux, idéal pour les grandes occasions.',
    specs: {
      Matière: 'Bazin / Soie / Wax',
      Coupe: 'Boubou ample',
      Finition: 'Broderie artisanale',
      Délai: '10 à 14 jours',
    },
    isNew: false,
  },
  {
    id: 416,
    name: 'Boubou Prestige ' + 17,
    category: 'boubous',
    categoryLabel: 'Boubou',
    image: '/boubous/b93896b8f44fe73250ed32b3258aca2d.jpg',
    price: '55 000 FCFA',
    rating: 4.9,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Boubou ample et majestueux, idéal pour les grandes occasions.',
    specs: {
      Matière: 'Bazin / Soie / Wax',
      Coupe: 'Boubou ample',
      Finition: 'Broderie artisanale',
      Délai: '10 à 14 jours',
    },
    isNew: false,
  },
  {
    id: 417,
    name: 'Boubou Prestige ' + 18,
    category: 'boubous',
    categoryLabel: 'Boubou',
    image: '/boubous/ba29fba11787f8faf5130c0cf79dee09.jpg',
    price: '55 000 FCFA',
    rating: 4.9,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Boubou ample et majestueux, idéal pour les grandes occasions.',
    specs: {
      Matière: 'Bazin / Soie / Wax',
      Coupe: 'Boubou ample',
      Finition: 'Broderie artisanale',
      Délai: '10 à 14 jours',
    },
    isNew: false,
  },
  {
    id: 418,
    name: 'Boubou Prestige ' + 19,
    category: 'boubous',
    categoryLabel: 'Boubou',
    image: '/boubous/c1bce33870570e8d3636862e20c75106.jpg',
    price: '55 000 FCFA',
    rating: 4.9,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Boubou ample et majestueux, idéal pour les grandes occasions.',
    specs: {
      Matière: 'Bazin / Soie / Wax',
      Coupe: 'Boubou ample',
      Finition: 'Broderie artisanale',
      Délai: '10 à 14 jours',
    },
    isNew: false,
  },
  {
    id: 419,
    name: 'Boubou Prestige ' + 20,
    category: 'boubous',
    categoryLabel: 'Boubou',
    image: '/boubous/c73c113d80c33eaba273dfe1f1f5ccd7.jpg',
    price: '55 000 FCFA',
    rating: 4.9,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Boubou ample et majestueux, idéal pour les grandes occasions.',
    specs: {
      Matière: 'Bazin / Soie / Wax',
      Coupe: 'Boubou ample',
      Finition: 'Broderie artisanale',
      Délai: '10 à 14 jours',
    },
    isNew: false,
  },
  {
    id: 420,
    name: 'Boubou Prestige ' + 21,
    category: 'boubous',
    categoryLabel: 'Boubou',
    image: '/boubous/cff8132da607d1d7bf24d9c2f923e062.jpg',
    price: '55 000 FCFA',
    rating: 4.9,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Boubou ample et majestueux, idéal pour les grandes occasions.',
    specs: {
      Matière: 'Bazin / Soie / Wax',
      Coupe: 'Boubou ample',
      Finition: 'Broderie artisanale',
      Délai: '10 à 14 jours',
    },
    isNew: false,
  },
  {
    id: 421,
    name: 'Boubou Prestige ' + 22,
    category: 'boubous',
    categoryLabel: 'Boubou',
    image: '/boubous/e2b733f1192adae702dc3125ebcd83b6.jpg',
    price: '55 000 FCFA',
    rating: 4.9,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Boubou ample et majestueux, idéal pour les grandes occasions.',
    specs: {
      Matière: 'Bazin / Soie / Wax',
      Coupe: 'Boubou ample',
      Finition: 'Broderie artisanale',
      Délai: '10 à 14 jours',
    },
    isNew: false,
  },
  {
    id: 422,
    name: 'Boubou Prestige ' + 23,
    category: 'boubous',
    categoryLabel: 'Boubou',
    image: '/boubous/f58e8455e0e20e5627833ee45950f8e4.jpg',
    price: '55 000 FCFA',
    rating: 4.9,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Boubou ample et majestueux, idéal pour les grandes occasions.',
    specs: {
      Matière: 'Bazin / Soie / Wax',
      Coupe: 'Boubou ample',
      Finition: 'Broderie artisanale',
      Délai: '10 à 14 jours',
    },
    isNew: false,
  },
  {
    id: 423,
    name: 'Boubou Prestige ' + 24,
    category: 'boubous',
    categoryLabel: 'Boubou',
    image: '/boubous/fa226a82c589993b1938f29f449c19d4.jpg',
    price: '55 000 FCFA',
    rating: 4.9,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Boubou ample et majestueux, idéal pour les grandes occasions.',
    specs: {
      Matière: 'Bazin / Soie / Wax',
      Coupe: 'Boubou ample',
      Finition: 'Broderie artisanale',
      Délai: '10 à 14 jours',
    },
    isNew: false,
  },
  {
    id: 424,
    name: 'Boubou Prestige ' + 25,
    category: 'boubous',
    categoryLabel: 'Boubou',
    image: '/boubous/fdf0c0d1e758137c2a75cda2a5b7bc2d.jpg',
    price: '55 000 FCFA',
    rating: 4.9,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Boubou ample et majestueux, idéal pour les grandes occasions.',
    specs: {
      Matière: 'Bazin / Soie / Wax',
      Coupe: 'Boubou ample',
      Finition: 'Broderie artisanale',
      Délai: '10 à 14 jours',
    },
    isNew: false,
  },
  {
    id: 425,
    name: 'Boubou Prestige ' + 26,
    category: 'boubous',
    categoryLabel: 'Boubou',
    image: '/boubous/téléchargement (1).png',
    price: '55 000 FCFA',
    rating: 4.9,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Boubou ample et majestueux, idéal pour les grandes occasions.',
    specs: {
      Matière: 'Bazin / Soie / Wax',
      Coupe: 'Boubou ample',
      Finition: 'Broderie artisanale',
      Délai: '10 à 14 jours',
    },
    isNew: false,
  },
  {
    id: 500,
    name: 'Collection Enfant ' + 1,
    category: 'enfant',
    categoryLabel: 'Enfant',
    image: '/enfant/0c2b029cd53819addfe040b77b836874.jpg',
    price: '15 000 FCFA',
    rating: 4.8,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Une création adorable et confortable, spécialement conçue pour les enfants.',
    specs: {
      Matière: 'Coton / Wax doux',
      Coupe: 'Coupe enfant ajustée',
      Finition: 'Couture soignée',
      Délai: '7 à 10 jours',
    },
    isNew: false,
  },
  {
    id: 501,
    name: 'Collection Enfant ' + 2,
    category: 'enfant',
    categoryLabel: 'Enfant',
    image: '/enfant/0c886b73f60cbadc20bea619f0c247b7.jpg',
    price: '15 000 FCFA',
    rating: 4.8,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Une création adorable et confortable, spécialement conçue pour les enfants.',
    specs: {
      Matière: 'Coton / Wax doux',
      Coupe: 'Coupe enfant ajustée',
      Finition: 'Couture soignée',
      Délai: '7 à 10 jours',
    },
    isNew: false,
  },
  {
    id: 502,
    name: 'Collection Enfant ' + 3,
    category: 'enfant',
    categoryLabel: 'Enfant',
    image: '/enfant/0d4b07d85a9f6c3a7ccf6c5e3cbfe576.jpg',
    price: '15 000 FCFA',
    rating: 4.8,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Une création adorable et confortable, spécialement conçue pour les enfants.',
    specs: {
      Matière: 'Coton / Wax doux',
      Coupe: 'Coupe enfant ajustée',
      Finition: 'Couture soignée',
      Délai: '7 à 10 jours',
    },
    isNew: false,
  },
  {
    id: 503,
    name: 'Collection Enfant ' + 4,
    category: 'enfant',
    categoryLabel: 'Enfant',
    image: '/enfant/1b49d929df004fb5376ce1432ce41803.jpg',
    price: '15 000 FCFA',
    rating: 4.8,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Une création adorable et confortable, spécialement conçue pour les enfants.',
    specs: {
      Matière: 'Coton / Wax doux',
      Coupe: 'Coupe enfant ajustée',
      Finition: 'Couture soignée',
      Délai: '7 à 10 jours',
    },
    isNew: false,
  },
  {
    id: 504,
    name: 'Collection Enfant ' + 5,
    category: 'enfant',
    categoryLabel: 'Enfant',
    image: '/enfant/2149bf347cab2e7e250be180eb020517.jpg',
    price: '15 000 FCFA',
    rating: 4.8,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Une création adorable et confortable, spécialement conçue pour les enfants.',
    specs: {
      Matière: 'Coton / Wax doux',
      Coupe: 'Coupe enfant ajustée',
      Finition: 'Couture soignée',
      Délai: '7 à 10 jours',
    },
    isNew: false,
  },
  {
    id: 505,
    name: 'Collection Enfant ' + 6,
    category: 'enfant',
    categoryLabel: 'Enfant',
    image: '/enfant/2a7d30a69c38bce6ffa435c1199fd1f4.jpg',
    price: '15 000 FCFA',
    rating: 4.8,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Une création adorable et confortable, spécialement conçue pour les enfants.',
    specs: {
      Matière: 'Coton / Wax doux',
      Coupe: 'Coupe enfant ajustée',
      Finition: 'Couture soignée',
      Délai: '7 à 10 jours',
    },
    isNew: false,
  },
  {
    id: 506,
    name: 'Collection Enfant ' + 7,
    category: 'enfant',
    categoryLabel: 'Enfant',
    image: '/enfant/2dd33e55e8ad6c09ae9e104777feb104.jpg',
    price: '15 000 FCFA',
    rating: 4.8,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Une création adorable et confortable, spécialement conçue pour les enfants.',
    specs: {
      Matière: 'Coton / Wax doux',
      Coupe: 'Coupe enfant ajustée',
      Finition: 'Couture soignée',
      Délai: '7 à 10 jours',
    },
    isNew: false,
  },
  {
    id: 507,
    name: 'Collection Enfant ' + 8,
    category: 'enfant',
    categoryLabel: 'Enfant',
    image: '/enfant/30afd692aac59f26a01923fa295a8e9f.jpg',
    price: '15 000 FCFA',
    rating: 4.8,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Une création adorable et confortable, spécialement conçue pour les enfants.',
    specs: {
      Matière: 'Coton / Wax doux',
      Coupe: 'Coupe enfant ajustée',
      Finition: 'Couture soignée',
      Délai: '7 à 10 jours',
    },
    isNew: false,
  },
  {
    id: 508,
    name: 'Collection Enfant ' + 9,
    category: 'enfant',
    categoryLabel: 'Enfant',
    image: '/enfant/37753b90d6769f578a2218c1ac468796.jpg',
    price: '15 000 FCFA',
    rating: 4.8,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Une création adorable et confortable, spécialement conçue pour les enfants.',
    specs: {
      Matière: 'Coton / Wax doux',
      Coupe: 'Coupe enfant ajustée',
      Finition: 'Couture soignée',
      Délai: '7 à 10 jours',
    },
    isNew: false,
  },
  {
    id: 509,
    name: 'Collection Enfant ' + 10,
    category: 'enfant',
    categoryLabel: 'Enfant',
    image: '/enfant/42d6de9e8be8c61a02929e1a18467739.jpg',
    price: '15 000 FCFA',
    rating: 4.8,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Une création adorable et confortable, spécialement conçue pour les enfants.',
    specs: {
      Matière: 'Coton / Wax doux',
      Coupe: 'Coupe enfant ajustée',
      Finition: 'Couture soignée',
      Délai: '7 à 10 jours',
    },
    isNew: false,
  },
  {
    id: 510,
    name: 'Collection Enfant ' + 11,
    category: 'enfant',
    categoryLabel: 'Enfant',
    image: '/enfant/45784f250a63d314a6ce5cee032e63ad.jpg',
    price: '15 000 FCFA',
    rating: 4.8,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Une création adorable et confortable, spécialement conçue pour les enfants.',
    specs: {
      Matière: 'Coton / Wax doux',
      Coupe: 'Coupe enfant ajustée',
      Finition: 'Couture soignée',
      Délai: '7 à 10 jours',
    },
    isNew: false,
  },
  {
    id: 511,
    name: 'Collection Enfant ' + 12,
    category: 'enfant',
    categoryLabel: 'Enfant',
    image: '/enfant/578cf14b9c7b58496ec487887bc5d7cd.jpg',
    price: '15 000 FCFA',
    rating: 4.8,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Une création adorable et confortable, spécialement conçue pour les enfants.',
    specs: {
      Matière: 'Coton / Wax doux',
      Coupe: 'Coupe enfant ajustée',
      Finition: 'Couture soignée',
      Délai: '7 à 10 jours',
    },
    isNew: false,
  },
  {
    id: 512,
    name: 'Collection Enfant ' + 13,
    category: 'enfant',
    categoryLabel: 'Enfant',
    image: '/enfant/5aa8c631ba5d6c1267c76f45dbd5f393.jpg',
    price: '15 000 FCFA',
    rating: 4.8,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Une création adorable et confortable, spécialement conçue pour les enfants.',
    specs: {
      Matière: 'Coton / Wax doux',
      Coupe: 'Coupe enfant ajustée',
      Finition: 'Couture soignée',
      Délai: '7 à 10 jours',
    },
    isNew: false,
  },
  {
    id: 513,
    name: 'Collection Enfant ' + 14,
    category: 'enfant',
    categoryLabel: 'Enfant',
    image: '/enfant/5c3b224a277b177a13fcce0b8badf801.jpg',
    price: '15 000 FCFA',
    rating: 4.8,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Une création adorable et confortable, spécialement conçue pour les enfants.',
    specs: {
      Matière: 'Coton / Wax doux',
      Coupe: 'Coupe enfant ajustée',
      Finition: 'Couture soignée',
      Délai: '7 à 10 jours',
    },
    isNew: false,
  },
  {
    id: 514,
    name: 'Collection Enfant ' + 15,
    category: 'enfant',
    categoryLabel: 'Enfant',
    image: '/enfant/5cbdd5ace2020282b1ca2c5efbcdf2d2.jpg',
    price: '15 000 FCFA',
    rating: 4.8,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Une création adorable et confortable, spécialement conçue pour les enfants.',
    specs: {
      Matière: 'Coton / Wax doux',
      Coupe: 'Coupe enfant ajustée',
      Finition: 'Couture soignée',
      Délai: '7 à 10 jours',
    },
    isNew: false,
  },
  {
    id: 515,
    name: 'Collection Enfant ' + 16,
    category: 'enfant',
    categoryLabel: 'Enfant',
    image: '/enfant/6a500e0e6e27d8f6266e3f5776c48327.jpg',
    price: '15 000 FCFA',
    rating: 4.8,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Une création adorable et confortable, spécialement conçue pour les enfants.',
    specs: {
      Matière: 'Coton / Wax doux',
      Coupe: 'Coupe enfant ajustée',
      Finition: 'Couture soignée',
      Délai: '7 à 10 jours',
    },
    isNew: false,
  },
  {
    id: 516,
    name: 'Collection Enfant ' + 17,
    category: 'enfant',
    categoryLabel: 'Enfant',
    image: '/enfant/6fcedd8043bc08f4a3ddac760160e934.jpg',
    price: '15 000 FCFA',
    rating: 4.8,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Une création adorable et confortable, spécialement conçue pour les enfants.',
    specs: {
      Matière: 'Coton / Wax doux',
      Coupe: 'Coupe enfant ajustée',
      Finition: 'Couture soignée',
      Délai: '7 à 10 jours',
    },
    isNew: false,
  },
  {
    id: 517,
    name: 'Collection Enfant ' + 18,
    category: 'enfant',
    categoryLabel: 'Enfant',
    image: '/enfant/8d941e8e999634f085ef17f68982e037.jpg',
    price: '15 000 FCFA',
    rating: 4.8,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Une création adorable et confortable, spécialement conçue pour les enfants.',
    specs: {
      Matière: 'Coton / Wax doux',
      Coupe: 'Coupe enfant ajustée',
      Finition: 'Couture soignée',
      Délai: '7 à 10 jours',
    },
    isNew: false,
  },
  {
    id: 518,
    name: 'Collection Enfant ' + 19,
    category: 'enfant',
    categoryLabel: 'Enfant',
    image: '/enfant/9c5408dce77e8349f4152239c4eeccb6.jpg',
    price: '15 000 FCFA',
    rating: 4.8,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Une création adorable et confortable, spécialement conçue pour les enfants.',
    specs: {
      Matière: 'Coton / Wax doux',
      Coupe: 'Coupe enfant ajustée',
      Finition: 'Couture soignée',
      Délai: '7 à 10 jours',
    },
    isNew: false,
  },
  {
    id: 519,
    name: 'Collection Enfant ' + 20,
    category: 'enfant',
    categoryLabel: 'Enfant',
    image: '/enfant/a4753d702227e67f812274e916baf04b.jpg',
    price: '15 000 FCFA',
    rating: 4.8,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Une création adorable et confortable, spécialement conçue pour les enfants.',
    specs: {
      Matière: 'Coton / Wax doux',
      Coupe: 'Coupe enfant ajustée',
      Finition: 'Couture soignée',
      Délai: '7 à 10 jours',
    },
    isNew: false,
  },
  {
    id: 520,
    name: 'Collection Enfant ' + 21,
    category: 'enfant',
    categoryLabel: 'Enfant',
    image: '/enfant/a5a4a8f145acb951e90a1c27b3f438f5.jpg',
    price: '15 000 FCFA',
    rating: 4.8,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Une création adorable et confortable, spécialement conçue pour les enfants.',
    specs: {
      Matière: 'Coton / Wax doux',
      Coupe: 'Coupe enfant ajustée',
      Finition: 'Couture soignée',
      Délai: '7 à 10 jours',
    },
    isNew: false,
  },
  {
    id: 521,
    name: 'Collection Enfant ' + 22,
    category: 'enfant',
    categoryLabel: 'Enfant',
    image: '/enfant/a8b03b0098bbb913d53ad95a8991a0e3.jpg',
    price: '15 000 FCFA',
    rating: 4.8,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Une création adorable et confortable, spécialement conçue pour les enfants.',
    specs: {
      Matière: 'Coton / Wax doux',
      Coupe: 'Coupe enfant ajustée',
      Finition: 'Couture soignée',
      Délai: '7 à 10 jours',
    },
    isNew: false,
  },
  {
    id: 522,
    name: 'Collection Enfant ' + 23,
    category: 'enfant',
    categoryLabel: 'Enfant',
    image: '/enfant/a8d6cd1b6eb147624a92a78ac3f5377e.jpg',
    price: '15 000 FCFA',
    rating: 4.8,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Une création adorable et confortable, spécialement conçue pour les enfants.',
    specs: {
      Matière: 'Coton / Wax doux',
      Coupe: 'Coupe enfant ajustée',
      Finition: 'Couture soignée',
      Délai: '7 à 10 jours',
    },
    isNew: false,
  },
  {
    id: 523,
    name: 'Collection Enfant ' + 24,
    category: 'enfant',
    categoryLabel: 'Enfant',
    image: '/enfant/b1c357850a183b7291b91875d1112839.jpg',
    price: '15 000 FCFA',
    rating: 4.8,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Une création adorable et confortable, spécialement conçue pour les enfants.',
    specs: {
      Matière: 'Coton / Wax doux',
      Coupe: 'Coupe enfant ajustée',
      Finition: 'Couture soignée',
      Délai: '7 à 10 jours',
    },
    isNew: false,
  },
  {
    id: 524,
    name: 'Collection Enfant ' + 25,
    category: 'enfant',
    categoryLabel: 'Enfant',
    image: '/enfant/b3eecf66e0038dd80f48ab8abfad8dc9.jpg',
    price: '15 000 FCFA',
    rating: 4.8,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Une création adorable et confortable, spécialement conçue pour les enfants.',
    specs: {
      Matière: 'Coton / Wax doux',
      Coupe: 'Coupe enfant ajustée',
      Finition: 'Couture soignée',
      Délai: '7 à 10 jours',
    },
    isNew: false,
  },
  {
    id: 525,
    name: 'Collection Enfant ' + 26,
    category: 'enfant',
    categoryLabel: 'Enfant',
    image: '/enfant/b7a26facaf44103b91b03ef240c0aeff.jpg',
    price: '15 000 FCFA',
    rating: 4.8,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Une création adorable et confortable, spécialement conçue pour les enfants.',
    specs: {
      Matière: 'Coton / Wax doux',
      Coupe: 'Coupe enfant ajustée',
      Finition: 'Couture soignée',
      Délai: '7 à 10 jours',
    },
    isNew: false,
  },
  {
    id: 526,
    name: 'Collection Enfant ' + 27,
    category: 'enfant',
    categoryLabel: 'Enfant',
    image: '/enfant/bf9df8254c2e2fb31c6dc77b758883f7.jpg',
    price: '15 000 FCFA',
    rating: 4.8,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Une création adorable et confortable, spécialement conçue pour les enfants.',
    specs: {
      Matière: 'Coton / Wax doux',
      Coupe: 'Coupe enfant ajustée',
      Finition: 'Couture soignée',
      Délai: '7 à 10 jours',
    },
    isNew: false,
  },
  {
    id: 527,
    name: 'Collection Enfant ' + 28,
    category: 'enfant',
    categoryLabel: 'Enfant',
    image: '/enfant/ca7fda4574847aec6e63ece0399713ed.jpg',
    price: '15 000 FCFA',
    rating: 4.8,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Une création adorable et confortable, spécialement conçue pour les enfants.',
    specs: {
      Matière: 'Coton / Wax doux',
      Coupe: 'Coupe enfant ajustée',
      Finition: 'Couture soignée',
      Délai: '7 à 10 jours',
    },
    isNew: false,
  },
  {
    id: 528,
    name: 'Collection Enfant ' + 29,
    category: 'enfant',
    categoryLabel: 'Enfant',
    image: '/enfant/cdd682305148254886218db598ef7c5e.jpg',
    price: '15 000 FCFA',
    rating: 4.8,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Une création adorable et confortable, spécialement conçue pour les enfants.',
    specs: {
      Matière: 'Coton / Wax doux',
      Coupe: 'Coupe enfant ajustée',
      Finition: 'Couture soignée',
      Délai: '7 à 10 jours',
    },
    isNew: false,
  },
  {
    id: 529,
    name: 'Collection Enfant ' + 30,
    category: 'enfant',
    categoryLabel: 'Enfant',
    image: '/enfant/d5261ea1a7e378c7aab1d04b4f390fb1.jpg',
    price: '15 000 FCFA',
    rating: 4.8,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Une création adorable et confortable, spécialement conçue pour les enfants.',
    specs: {
      Matière: 'Coton / Wax doux',
      Coupe: 'Coupe enfant ajustée',
      Finition: 'Couture soignée',
      Délai: '7 à 10 jours',
    },
    isNew: false,
  },
  {
    id: 530,
    name: 'Collection Enfant ' + 31,
    category: 'enfant',
    categoryLabel: 'Enfant',
    image: '/enfant/dca00bd0d5de268e0197a9cf4a35098a.jpg',
    price: '15 000 FCFA',
    rating: 4.8,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Une création adorable et confortable, spécialement conçue pour les enfants.',
    specs: {
      Matière: 'Coton / Wax doux',
      Coupe: 'Coupe enfant ajustée',
      Finition: 'Couture soignée',
      Délai: '7 à 10 jours',
    },
    isNew: false,
  },
  {
    id: 531,
    name: 'Collection Enfant ' + 32,
    category: 'enfant',
    categoryLabel: 'Enfant',
    image: '/enfant/e83a76b8b247d3f7c565bde60922358e.jpg',
    price: '15 000 FCFA',
    rating: 4.8,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Une création adorable et confortable, spécialement conçue pour les enfants.',
    specs: {
      Matière: 'Coton / Wax doux',
      Coupe: 'Coupe enfant ajustée',
      Finition: 'Couture soignée',
      Délai: '7 à 10 jours',
    },
    isNew: false,
  },
  {
    id: 532,
    name: 'Collection Enfant ' + 33,
    category: 'enfant',
    categoryLabel: 'Enfant',
    image: '/enfant/ede884d7bb71ef9b485c4ca4c962c41c.jpg',
    price: '15 000 FCFA',
    rating: 4.8,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Une création adorable et confortable, spécialement conçue pour les enfants.',
    specs: {
      Matière: 'Coton / Wax doux',
      Coupe: 'Coupe enfant ajustée',
      Finition: 'Couture soignée',
      Délai: '7 à 10 jours',
    },
    isNew: false,
  },
  {
    id: 533,
    name: 'Collection Enfant ' + 34,
    category: 'enfant',
    categoryLabel: 'Enfant',
    image: '/enfant/fc8d61af2f18a94336044cfdba387d63.jpg',
    price: '15 000 FCFA',
    rating: 4.8,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Une création adorable et confortable, spécialement conçue pour les enfants.',
    specs: {
      Matière: 'Coton / Wax doux',
      Coupe: 'Coupe enfant ajustée',
      Finition: 'Couture soignée',
      Délai: '7 à 10 jours',
    },
    isNew: false,
  },
  {
    id: 534,
    name: 'Collection Enfant ' + 35,
    category: 'enfant',
    categoryLabel: 'Enfant',
    image: '/enfant/ffae998133560419b8d5ae97972a3e57.jpg',
    price: '15 000 FCFA',
    rating: 4.8,
    reviews: Math.floor(Math.random() * 40) + 5,
    badge: null,
    description: 'Une création adorable et confortable, spécialement conçue pour les enfants.',
    specs: {
      Matière: 'Coton / Wax doux',
      Coupe: 'Coupe enfant ajustée',
      Finition: 'Couture soignée',
      Délai: '7 à 10 jours',
    },
    isNew: false,
  },
];

export const banners = [
  {
    id: 1,
    badge: 'Nouvelle Collection',
    title: 'Automne\nGrand Chic',
    subtitle: '15% de remise sur toute nouvelle commande',
    image: robeWax,
    modelImage: boubouBordeaux,
    bg: 'linear-gradient(135deg, #1a0a00 0%, #3d1a00 100%)',
  },
  {
    id: 2,
    badge: 'Collection Prestige',
    title: 'Soirée\nEtoilée',
    subtitle: 'Nos robes de soirée exclusives',
    image: robeNoire,
    modelImage: robeNoire,
    bg: 'linear-gradient(135deg, #0d0d1a 0%, #1a0d2e 100%)',
  },
  {
    id: 3,
    badge: 'Sur-Mesure',
    title: 'Votre Tenue\nPersonnalisée',
    subtitle: 'Confectionnée selon vos mensurations exactes',
    image: ensembleBleu,
    modelImage: ensembleBleu,
    bg: 'linear-gradient(135deg, #001a0d 0%, #003d1a 100%)',
  },
];

export const services = [
  {
    id: 1,
    name: 'Couture Sur Mesure',
    description:
      'Chaque vêtement est confectionné à vos mesures exactes pour un tombé parfait et un confort incomparable. Prise de mesures gratuite dans notre atelier.',
    icon: 'scissors',
    color: '#FF4D00',
    bg: 'linear-gradient(135deg, #FF4D00, #FF6B2B)',
  },
  {
    id: 2,
    name: 'Stylisme & Conseil',
    description:
      'Notre styliste vous accompagne dans le choix des tissus, des couleurs et des coupes qui mettront en valeur votre silhouette et votre personnalité.',
    icon: 'sparkle',
    color: '#9B59B6',
    bg: 'linear-gradient(135deg, #9B59B6, #8E44AD)',
  },
  {
    id: 3,
    name: 'Retouches & Ajustements',
    description:
      'Retouche de vêtements existants, transformation et ajustements pour que chaque tenue vous aille à la perfection.',
    icon: 'tool',
    color: '#27AE60',
    bg: 'linear-gradient(135deg, #27AE60, #2ECC71)',
  },
  {
    id: 4,
    name: 'Robes de Cérémonie',
    description:
      'Spécialisation dans les tenues de mariage, baptême, anniversaire et cérémonies officielles. Des créations uniques pour vos moments inoubliables.',
    icon: 'heart',
    color: '#E91E63',
    bg: 'linear-gradient(135deg, #E91E63, #AD1457)',
  },
  {
    id: 5,
    name: 'Tenues Professionnelles',
    description:
      'Uniformes de bureau, tenues corporatives et collections pour entreprises. Style professionnel alliant élégance et fonctionnalité.',
    icon: 'briefcase',
    color: '#1A73E8',
    bg: 'linear-gradient(135deg, #1A73E8, #1565C0)',
  },
  {
    id: 6,
    name: 'Livraison à Domicile',
    description:
      'Livraison dans tout Parakou et environs. Profitez de vos créations sans vous déplacer. Prise en charge rapide et soigneuse.',
    icon: 'truck',
    color: '#F59E0B',
    bg: 'linear-gradient(135deg, #F59E0B, #D97706)',
  },
];
